spring:
  datasource:
    url: jdbc:mysql://<DB_HOST>:<PORT>/<DB_NAME>?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none  # ✅ 기존 데이터 유지
    show-sql: true  # ✅ SQL 로그 콘솔 출력 활성화
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        function_contributor: com.example.config.MySQLCustomDialect
        format_sql: true  # ✅ SQL을 보기 좋게 포맷팅

  redis:
    host: 127.0.0.1
    port: 6380