spring:
  datasource:
    url: jdbc:mysql://[DB_HOST]]:[DB_PORT]/[DB_NAME]?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        function_contributor: com.example.config.MySQLCustomDialect
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/init/dummy.sql

  redis:
    host: [REDIS_HOST]
    port: [REDIS_PORT]

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never

  redis:
    host: localhost
    port: 6378