INSERT INTO movies (title, rating, release_date, thumbnail_image, running_time, genre, created_at, updated_at)
SELECT
    CONCAT('Movie_', n) AS title,
    CASE FLOOR(RAND() * 3)
        WHEN 0 THEN 'R_12'
        WHEN 1 THEN 'R_15'
        ELSE 'R_19'
    END AS rating,
    DATE_ADD('2010-01-01', INTERVAL FLOOR(RAND() * 5843) DAY) AS release_date,
    CONCAT('movie_', n, '.jpg') AS thumbnail_image,
    FLOOR(RAND() * 60 + 90) AS running_time,
    CASE FLOOR(RAND() * 12)
        WHEN 0 THEN 'ACTION'
        WHEN 1 THEN 'DRAMA'
        WHEN 2 THEN 'SF'
        WHEN 3 THEN 'HORROR'
        WHEN 4 THEN 'ROMANCE'
        WHEN 5 THEN 'COMEDY'
        WHEN 6 THEN 'THRILLER'
        WHEN 7 THEN 'FANTASY'
        WHEN 8 THEN 'MYSTERY'
        WHEN 9 THEN 'ADVENTURE'
        WHEN 10 THEN 'CRIME'
        ELSE 'ANIMATION'
    END AS genre,
    NOW(), NOW()
FROM (SELECT @n := @n + 1 as n
      FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t1,
           (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t2,
           (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t3,
           (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t4,
           (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t5,
           (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t6,
           (SELECT @n := 0) tmp) t7
LIMIT 10000;

SELECT * FROM movies;

INSERT INTO screenings (date, start_time, end_time, movie_id, theater_id, created_at, updated_at)
SELECT
    DATE_ADD('2024-01-01', INTERVAL FLOOR(RAND() * 365) DAY) AS date,
    TIME(SEC_TO_TIME(FLOOR(RAND() * 86400))) AS start_time,
    DATE_ADD(TIME(SEC_TO_TIME(FLOOR(RAND() * 86400))), INTERVAL FLOOR(RAND() * 3) HOUR) AS end_time,
    FLOOR(RAND() * 10000) + 1 AS movie_id,
    FLOOR(RAND() * 100) + 1 AS theater_id,
    NOW(), NOW()
FROM (SELECT 1 FROM
             (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) a,
             (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) b,
             (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) c,
             (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) d,
             (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) e) t;

select * from screenings;

INSERT INTO theaters (name, created_at, updated_at)
SELECT
    CONCAT('Theater_', n) AS name,
    NOW(), NOW()
FROM (SELECT @n := @n + 1 as n
      FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t1,
           (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t2,
           (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4) t3,
           (SELECT @n := 0) tmp) t4
LIMIT 100;
SELECT * FROM theaters;