dependencies {
    // mysql
    implementation 'mysql:mysql-connector-java:8.0.33'
    runtimeOnly 'com.mysql:mysql-connector-j'

    // redis
    api 'org.springframework.boot:spring-boot-starter-data-redis'
    api 'org.redisson:redisson:3.22.0'

    // test 환경 db
    runtimeOnly 'com.h2database:h2'

    // 날짜, 시간 형식
    implementation('com.fasterxml.jackson.datatype:jackson-datatype-jsr310')

    // JPA
    api ('org.springframework.boot:spring-boot-starter-data-jpa')
    implementation 'org.hibernate:hibernate-core:6.6.11.Final'

    // QueryDsl
    implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
    annotationProcessor "com.querydsl:querydsl-apt:5.0.0:jakarta"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"
}