dependencies {
    implementation project(':domain')
    implementation project(':common')
    // actuator에서 db, redis health 정보를 확인하려면,
    // 해당 설정이 포함된 infra 모듈이 실행 주체(api)의 classpath에 직접 포함되어야 함.
    implementation project(':infra')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
}